name: Deploy .NET 9 API to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: https://brewbox.azurewebsites.net  # Replace with your App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'     # Path to your project ('.' if at repository root)
  DOTNET_VERSION: '9.0.x'            # .NET 9 version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish